In [1]:
#reading all the .doc and .docx file in given path folder "C:\\Resumes\\Peoplesoftresumes"

In [3]:
pip install docx2txt

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: docx2txt in c:\users\rajiv\appdata\roaming\python\python310\site-packages (0.8)
Note: you may need to restart the kernel to use updated packages.

In [21]:
import pandas as pd
import docx2txt
import glob

# Create empty lists to store data and file names
data = []
file_names = []

# Use glob to get paths of all .doc and .docx files in folder
files = glob.glob("C:\\Users\\rajiv\\OneDrive\\Desktop\\resumedataset\\Resumes\\Peoplesoft resumes\\*.docx") + glob.glob("C:\\Users\\rajiv\\OneDrive\\Desktop\\resumedataset\\Resumes\\Peoplesoft resumes\\*.doc")

# Loop through files
for file in files:
    # Get file name and append to file_names list
    file_name = file.split("\\")[-1]
    file_names.append(file_name)
    # Read text data from file and append to data list
    if file_name.endswith('.docx'):
        text = docx2txt.process(file)
    else:
        with open(file, 'rb') as f:
            text = str(f.read())
    data.append(text)

# Create a dataframe
df = pd.DataFrame({'File Name': file_names, 'Text Data': data})

In [22]:
df

,File Name,Text Data
0,Peoplesoft Admin_AnubhavSingh.docx,Anubhav Kumar Singh\t\t\n\n\n\nCore Competenci...
1,Peoplesoft Admin_G Ananda Rayudu.docx,G. Ananda Rayudu \n\n\t\t https://www.li...
2,Peoplesoft Admin_Gangareddy.docx,PeopleSoft Database Administrator\n\n ...
3,Peoplesoft Admin_Murali.docx,Classification: Internal\n\nClassification: In...
4,Peoplesoft Admin_Priyanka Ramadoss.docx,"Priyanka Ramadoss\n\n\t61/46, MountPleasant, \..."
5,Peoplesoft Admin_SirazuddinMohammad.docx,"SIRAZUDDIN M\n\n\tBangalore, INDIA\t\n\n\n\n\n..."
6,Peoplesoft Admin_srinivasarao.docx,PEOPLESOFT Administrator\n\n\n\n\n\nSRINIVAS.K...
7,Peoplesoft Admin_Varkala Vikas.docx,PeopleSoft Admin\n\nVARKALA VIKAS\n\n\n\nCaree...
8,Peoplesoft Admin_Vinod Akkala.docx,Vinod Akkala ...
9,PeopleSoft DBA_Ganesh Alladi.docx,PeopleSoft Admin/PeopleSoft DBA\n\n\n\nGanesh ...
10,PeopleSoft DBA_Vivekanand Sayana.docx,PeopleSoft Administration\n\n \n\nVivekanand S...
11,Peoplesoft Finance_Arun Venu.docx,Arun Venu\n\n\n\n\t EXPERIENCE SUMMARY\t\n\n\...
12,Peoplesoft Finance_Pritam Biswas.docx,Personal Details\t\t\n\n\n\nName\n\nPritam Bis...
13,Peoplesoft Finance_Rahul Ahuja.docx,Rahul Ahuja\n\n-------------------------------...
14,Peoplesoft FSCM_HariNarayana.docx,Hari Narayana \t\t \n\n\t\n\n\n\n...
15,Peoplesoft FSCM_Murali.docx,Murali\t\t \n\n\t\n\n\n\n\n\n\n\n\n\n\n\...
16,Peoplesoft FSCM_PriyabrataHota.docx,Priyabrata Hota\n\n\n\n\n\nCAREER OBJECTIVE\t\...
17,Peoplesoft FSCM_R Ahmed.docx,R Ahmed ...
18,Peoplesoft FSCM_SUJATHA.docx,Tanna Sujatha \n\n\n\n\n\n\n\nOBJECTIVE\n\nSee...
19,Resume_Subha Santosh_Peoplesoft FSCM.docx,C O N T A C T :\n\n\n\nAddress: Manyata Tech P...

In [23]:
print(df.iloc[12]['Text Data'])

Personal Details



Name

Pritam Biswas

Date Of Birth

26/01/1996

Present Location

Pune









	Experience Summary

4.1 years- Experience of Development, Support and maintenance, Upgrade in PeopleSoft Project in IBM.

Currently working in PeopleSoft implementation project in Accenture.

Exposure of working in Finance module and HCM module.

Technical knowledge and hands on experience in People tools versions 9.1 and 9.2

Have worked on PeopleSoft HRMS application versions 8.55 to 8.58

Have worked on technical aspects as: creating PeopleSoft Objects like Field, Record, Page, Component, File Layout, Application Engine, BI Publisher Report, Form etc.

Have worked on creating SQRs.

Have worked on creating Application Engine.

Have worked on creating BI Publisher report.

Have worked on creating PS Query.

Have hands-on experience in generic Event mapping.

Have worked on PeopleSoft Job and Job Stream management through IWS.

Have Basic idea of Control M to Schedule and monitor Jobs.

Have basic idea of Service Now, JIRA and PHIRE as ticketing tool.

	Skills

	Technical Skills

Technologies: PeopleSoft- ERP, HRMS Applications V 8.X

Operating Systems: Windows (all versions till 10), Mac OS (10.9 to 10.13)

Programming Language: C, Python (Beginner), PeopleCode, SQR

Tools: People Tools 8.54 to 8.58, Oracle SQL Developer, App Designer, Tectia Client, ServiceNow, WinScp, IWS, Control M.

Databases: Oracle. DB2, SQL Server 2005

Reporting Tools: SQR, PS Query, BI Publisher

Industries: HCM, Finance

	Soft Skills

Dedicated to work.

Eager to adopt new skills.

Good communication and Presentation Skill in English, Hindi, Bengali.

Interested in solving analytical problems.

Good Team player.

Can adopt any hazardous Situations

Educational Qualifications

Degree

Institution

Stream

Percentage/ CGPA

Year Of Passing

B.Tech

National Institute Of Technology Durgapur

Electrical Engineering

8.41

2017

12th Higher Secondary

Burdwan Municipal High School

Pure Science (includes Computer Science)

82.24

2013

10th Secondary

Burdwan Municipal High School

All Subjects

87.2

2011



Job History

IBM India Pvt Ltd

July 2017 to May 2020

Accenture India

June 2020 ti till date



Professional Summary

Employer / Client

IBM India / CitiGroup Finance

Project

PeopleSoft Production Support and Maintenance

Tenure

October 2017-December 2018

Responsibilities

Provide Technical Support

Provide Analysis of any PeopleSoft related issue coming to Level 2 support Team

Working and supporting in 6 Applications: CRC, ETL, APSS, CitiGL, CBSI, FRS.

Support User directly when issue comes.

Host Team meetings to update and manage Status of all issues.

Create Calendar for Autosys Jobs, Batch files to run.

Support on Green Zones and Production Checkouts.

Make Daily/Weekly Reports in various applications

Analyze and solve Problem Tickets, Incidents

Can handle ServiceNow tool to create, modify Incident Tickets, Change Requests

Have Worked on Full NDM Certificate Update, NDM Testing and got successful signoff from 16 clients.

Have worked on DSMT Load Activity and did Checkout from team

Have worked on COB Test Activity and provided Checkout from Team.

 Experience in monitoring Jobs and analyzing Failures from Process Monitor, App Designer, SQL Developer, Tectia Client

Attend Meetings with Clients and update on behalf of Team.





Employer / Client

IBM India / AXA Insurance Uprade

Project

PeopleSoft HCM Development and Upgrade

Tenure

January 2019-September 2019

Responsibilities

Assigned in AXA upgrade Team as a developer for upgrading Peoplesoft Version 9.1 to 9.2.

Have worked in Mapping and tracing all steps for a Peoplesoft Upgrade Project.

Have worked on identifying different objects like Bolt-on, Custom, Peoplesoft modified objects.

Have worked on Retrofitting Peoplesoft objects to make a development environment.

Have worked on Data Reconciliation process in every intermediate environment.

Have worked on SQR analysis, creating PS Query, Pages, records, components, menus etc.

Have worked in Batch Process running in each intermediate phase for Testing purpose.



Employer / Client

IBM India / AXA Insurance Support

Project

PeopleSoft HCM Enhancement and Support

Tenure

October 2019-Present

Responsibilities

Worked on Basic enhancement and support.

Have worked in creating PS Query

Have created SQR, modified SQR.

Have worked in Job management and Job Scheduling for PeopleSoft through IWS.

Give Technical Support as L2 team.



Employer / Client

Accenture India / Florida PALM Project

Project

PeopleSoft Finance implementation

Tenure

June 2020-Present

Responsibilities

Currently working on developing interfaces, reports, workflow, form, PS Query, BI Publisher from scratch.

Worked on creating App Engine, App package, Component Interface, multi-level Page, XML Report.

Supporting as resolving Service request raised while doing production release. Tickets are expected to be resolved within stipulated timeline.

Mentor Associate developers and supervise their tasks.



Achievements

Got Acknowledgement from Client for Excellent, Uninterrupted and Professional Support within 6 months.

Got acknowledged for leading Yearly COB Activity in 8 months experience.

Got Manager’s Choice Award for 4 times in 2 years from 2 projects.

Got 5 IBMer’s appreciation in 2 years from 2 Projects.

Have been awarded with Eminence and Excellence Award, IBM.

Had been awarded with Rising Star Award, IBM.

Have been awarded with Shining Star Award, Accenture.

Recipient of Central Sector Scheme of Scholarship for College and University for year 2013, 2014 .

Recipient of Dr. B. R. Ambedkar Medha Puraskar 2011 .



Extra Curriculars

Singing

Sketching

===========================================================================================

In [24]:
#adding class as peoplesoft foe all the resume of folder pwoplesoft

In [25]:
df['class'] = "peoplesoft"

In [26]:
df.to_csv("peoplesoft.csv", index=False)

In [27]:
#reading all the .doc and .docx file in given path folder "C:\\Resumes\\SQL Developer Lightning insight"

In [28]:
import pandas as pd
import docx2txt
import glob

# Create empty lists to store data and file names
data = []
file_names = []

# Use glob to get paths of all .doc and .docx files in folder
files = glob.glob("C:\\Users\\rajiv\OneDrive\\Desktop\\resumedataset\\Resumes\\SQL Developer Lightning insight\\*.docx") + glob.glob("C:\\Users\\rajiv\OneDrive\\Desktop\\resumedataset\\Resumes\\SQL Developer Lightning insight\\*.doc")

# Loop through files
for file in files:
    # Get file name and append to file_names list
    file_name = file.split("\\")[-1]
    file_names.append(file_name)
    # Read text data from file and append to data list
    if file_name.endswith('.docx'):
        text = docx2txt.process(file)
    else:
        with open(file, 'rb') as f:
            text = str(f.read())
    data.append(text)

# Create dataframe
df = pd.DataFrame({'File Name': file_names, 'Text Data': data})

In [29]:
df

,File Name,Text Data
0,Anil kumar.docx,ANIL KUMAR MADDUKURI \t\t\n\nSQL & MSBI Devel...
1,AradhanaTripathi[4_0].docx,Aradhana Tripathi\n\n\n\nCurrent Location: Gac...
2,Buddha Vamsi.docx,BUDDHA VAMSI ...
3,kamballapradeep.docx,KAMBALLA PRADEEP ...
4,Nazeer Basha.docx, Hyderabad\n\n\nNazeer Basha\n\nSQL and Power...
5,Neeraj Mishra.docx,Resume\n\nName : Neeraj Mishra\n\n\n\nExp...
6,premsai.docx,SQL DEVELOPER\n\nName: - Bandi prem sai\n\n\...
7,Priyanka L.docx,SQL SERVER DEVELOPER\n\n\n\n\n\nPriyanka L ...
8,PSyamKumar[2_3].docx,SQL SERVER DEVELOPER\n\n\n\n\n\nP. Syam Kumar ...
9,Rajupavanakumari[2_10].docx,RAJU PAVANA KUMARI\n\n\n\n\t\n\n\tProfessional...
10,Ramalakshmi K.docx,resume\n\n\n\n\n\n\t\t\t\t\t\t\t\t\t\t\t\tRama...
11,RameshNataru[3_4].docx,Name: Ramesh\n\n\t\n\n\tCareer Objective: \n\n...
12,Tatikonda Kiran Kumar.docx,Tatikonda Kiran Kumar.\n\n\n\n\n\n\n\n\t\tCare...
13,Vinod B.docx,SQL AND MSBI DEVELOPER\n\nSQL AND MSBI DEVELOP...

In [30]:
print(df.iloc[12]['Text Data'])

Tatikonda Kiran Kumar.







		Career objective



A rewarding opportunity in a growth-oriented company, this gives me scope to apply my knowledge and become an active member of a team to work. I am seeking responsible position as to use my diverse skills, experience and advanced technical knowledge to develop innovative solutions.



		Experience Summary



I.T. Professional with 3.2 years of total experience in MICROSOFT SQL SERVER Development with a talent for analyzing problems, developing and simplifying procedures and finding innovative solutions.

Experience in writing joins and set operators in order to pull data from multiple tables and combines data from multiple select queries results.s

Good knowledge in creating constraints on tables.

Hands on experience in Sub queries in order to store temporary result set of select queries.

Good knowledge on CTE (Common table expression) and Recursive CTE.

Experience In using system functions (aggregate functions, date functions, string functions, rank functions, cast and convert functions) in order to meet business criteria.

Good knowledge in using temp tables and table variables in order to store data temporary purpose.

Extensive experience with SQL Server and T-SQL in constructing

Stored procedures, user defined functions, dynamic sql, Cursor.

Good Knowledge on triggers (for triggers, instead of triggers).

Good knowledge in implementing TCL (Transactional control language) inside stored procedures.

Good knowledge on Views.

Knowledge on SQL Indexes and Performance Tuning.

Basic Knowledge on Normalization and Normalization forms.

Good knowledge in using sql server import export wizard in order to dump data into database from multiple sources like flat files and excel files etc.



		Education Qualification

. M.com SV University Education, during 2014-2016.

	Bachelor of computer application in SV University Education, during 20011-2014.

	 Intermediate from Board of Intermediate Education, during 2009-2011.

	S.S.C from Secondary Board Of Education during 2009.







		Professional Experience



Duration

Organisation

Designation

March 2018 to till date

OSCORP Information systems

      Software Engineer



		Project Details



Project Name

Digital Health Care System

Team Size

8

Start Date

March 2018

End Date

Till date

Description

E-Knowledge in health care system is to provide the browser to get appointments from a doctor through internet instead of going there and fixing an appointment. In Doctor’s side they can view their appointments and prescribe medicine for their patients-Knowledge in health care system maintains patient’s prescriptions so that their medical details are always available in internet, which will be more convenient for the patients. This will be more comfortable for the patient. Patient details and prescriptions are maintained confidentially. There are four modules in E-knowledge in Health care system they are Patient module, Doctor module, Administrator module, General  user module

Role & Contribution

	Coordinating the Developing activities with the development team And QA team.

	Developed sql joins based as per business requirements.

Writing and worked on complex stored procedures, triggers, functions and views.

Writing complex SQL queries using joins, sub queries and correlated sub queries to retrieve data from the database.

Reviewing and Execution of Test cases.

Modifying existing code according to the client requirement.



Technologies

SQL Server 2008R2.

Client

Norton’s Hospital



		Personal Information



		Date of Birth		:	12 July 1994.

		Sex			:	Male

		Marital Status		:	Single.

		Nationality		:	Indian.

		Linguistic Abilities	:	Telugu and English.

	         Current Location 	:	Hyderabad.

In [31]:
df['class'] = "SQL_Developer"

In [32]:
df.head()

,File Name,Text Data,class
0,Anil kumar.docx,ANIL KUMAR MADDUKURI \t\t\n\nSQL & MSBI Devel...,SQL_Developer
1,AradhanaTripathi[4_0].docx,Aradhana Tripathi\n\n\n\nCurrent Location: Gac...,SQL_Developer
2,Buddha Vamsi.docx,BUDDHA VAMSI ...,SQL_Developer
3,kamballapradeep.docx,KAMBALLA PRADEEP ...,SQL_Developer
4,Nazeer Basha.docx, Hyderabad\n\n\nNazeer Basha\n\nSQL and Power...,SQL_Developer

In [33]:
df.to_csv("SQL_Developer.csv", index=False)

In [34]:
#reading all the .doc and .docx file in given path folder "C:\\Resumes\\workday resumes"

In [35]:
import pandas as pd
import docx2txt
import glob

# Create empty lists to store data and file names
data = []
file_names = []

# Use glob to get paths of all .doc and .docx files in folder
files = glob.glob("C:\\Users\\rajiv\\OneDrive\\Desktop\\resumedataset\\Resumes\\workday resumes\\*.docx") + glob.glob("C:\\Users\\rajiv\\OneDrive\\Desktop\\resumedataset\\Resumes\\workday resumes\\*.doc")

# Loop through files
for file in files:
    # Get file name and append to file_names list
    file_name = file.split("\\")[-1]
    file_names.append(file_name)
    # Read text data from file and append to data list
    if file_name.endswith('.docx'):
        text = docx2txt.process(file)
    else:
        with open(file, 'rb') as f:
            text = str(f.read())
    data.append(text)

# Create dataframe
df = pd.DataFrame({'File Name': file_names, 'Text Data': data})

In [36]:
df

,File Name,Text Data
0,ChinnaSubbarayuduM_Hexaware.docx,Chinna Subbarayudu M\n\nDOB: 06th March 1994\n...
1,Gopi Krishna_Hexaware.docx,Name : Gopi Krishna Reddy\n\n\t\t\t\t ...
2,Hari Krishna M_Hexaware.docx,Hari Krishna M\n\n\n\n\n\nSummary:\n\nA result...
3,Harikrishna Akula_Hexaware.docx,Harikrishna Akula ...
4,Hima Mendu_Hexaware.docx,HIMA.MENDU\n\n\t \n\n\n\nCareer Objective\n\n...
5,Himaja G_(Hexaware).docx,G Himaja\n\n ...
6,J. Sumanth Royal_Hexaware.docx,Name:\tJ. Sumanth Royal.\n\n\t\n\nPROFESSIONAL...
7,Jyotiverma_Heaware.docx,JYOTI VERMA\t\t\t\t\t\n\n\n\nPROFESSIONAL SUMM...
8,Madeeswar A_Hexaware.docx,Madeeswar A\n\n\t\n\n\t\t\n\n\t\t\tPROFILE SUM...
9,MooraboyinaGuravaiah_Hexaware.docx,Mooraboyina Guravaiah\n\nWorkday Integration S...
10,Naresh Babu Cherukuri_Hexaware.docx,Name\t: Naresh Babu Cherukuri\n\n\n\nObjective...
11,P V Sai Krishna_ Hexaware.docx,VENKATA SAIKRISHNA\n\n Workday Consultant\n\n\...
12,Punugoti Swetha_Hexaware.docx,Punugoti Swetha\n\nWorkday Technical Consultan...
13,RahulM_Hexaware.docx,Workday HCM Techno functional Consultant ...
14,RameshP_Hexaware.docx,Ramesh A\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t...
15,ShireeshKumar_Hexaware.docx,Shireesh Balasani ...
16,Sri Krishna S_Hexaware.docx,Workday Integration Consultant\n\n\n\nName ...
17,Srikanth-Hexaware.docx,Srikanth (WORKDAY hCM Consultant)\t ...
18,SSKumar_Hexaware.docx,WORKDAY | HCM | FCM\n\nName \t\t: Kumar S.S\n\...
19,Venkateswarlu B_Hexaware.docx,Venkateswarlu.B\t\t\t\t\t\t\t\tWorkday Consult...
20,Vinay Kumar_Hexaware.docx,Vinay kumar .v\nWorkday Functional Consultant\...

In [37]:
print(df.iloc[12]['Text Data'])

Punugoti Swetha

Workday Technical Consultant



PROFILE SUMMARY



3.3 years of IT experience as Workday HCM Technical Consultant in Workday Support and Enhancement Projects.

Developed and maintained custom-report types (Advanced, Matrix) using report writer tool.

Worked on custom report and calculated fields, Schedule the reports as per client requirements.

Worked on Alerts and Notification for reports.

Worked on Report Transfers ownership task and removed unnecessary reports from schedules.

Worked on Work-lets and Dashboards, Set up announcements, set up Hyperlink to help on account.

Developed Core connector and Document Transformation integrations to get changes file of CSV format from XML Output.

Good experience with Core Connector worker to work on employee demographics and build Benefit integrations and Account provisioning integrations.

Created Inbound/Outbound integrations using workday studio, core/cloud connectors,

using EIB’s, document transformation process.

Design, build or maintain integrations of all types: reports, EIB, Core Connectors, payroll connectors, and Studio.

Worked on BIRT report, created BIRT report as per client requirement like change the view of report

Used delivered ETV/XTT functions from a Custom XSLT file to transform the content into a CSV file format.

Worked on Employee Type and Contract type for local and global (Different countries).

Worked on Business Process Level security and Domains level security.

Interact with clients and vendor on a regular basis for gathering/clarifying business requirements, testing and deployment.

Worked on Delegation, Reassignments, Shift Creation, and Dashboard





EMPLOYMENT DETAILS



Working as Workday Consultant in FireEye, Bangalore From June 2018 to Till Date





SKILLS



Workday Skills

Report Writer, Core HCM, Business process, Security, EIB, Core connector, DT, Basic Studio, Birt

Programming Languages

XML,XSLT



CAREER CONTOUR



Professional Experience:



	Company	: FireEye

	Role	: Workday Consultant

	Duration	: June 2018 – Till Date

	Project	: Workday Support and Enhancement



Description:



FireEye is a publicly traded cybersecurity company headquartered in Milpitas, California. It has been involved in the detection and prevention of major cyber attacks. It provides hardware, software, and services to investigate cybersecurity attacks, protect against malicious software, and analyze IT security risks.



Responsibilities:



Gathering the client business requirements and configure the Workday solution

Estimation and planning for Change Request (CR) execution

Developed Core connector and Document Transformation integrations to get changes file of CSV format from XML Output.

Good experience with Core Connector worker to work on employee demographics and build Benefit integrations and Account provisioning integrations.

Created Inbound/Outbound integrations using workday studio, core/cloud connectors,

using EIB’s, document transformation process.

Design, build or maintain integrations of all types: reports, EIB, Core Connectors, payroll connectors, or Studio.

Worked on fixing the issues based on client requirement.

Responsible for scheduling the related interface programs and Monitoring them timely basis

Used delivered ETV/XTT functions from a Custom XSLT file to transform the content into a CSV file format.

Created design and technical documents.

Configuring Delivery Service, Sequence Generators and Business Process Definitions for Integration systems.

Worked with Onshore coordinators for requirements gathering.

Providing Daily status reports to onshore managers and handling other project management activities such as Daily Status discussion, reporting, work assignments.

Modifications and implementing multiple enhancements to existing Integrations, Custom Reports, Calculated field and XSLT.

Experience in creating all kinds of custom reports like Simple and Advanced.

Worked on Security Groups, Configured User based security group, Role Based security groups and created intersection security group.

Worked on Business Process Level security and Domains level security.





SCHOLASTICS



	Bachelor of Technology(B.Tech),	QIS College Of Engineering And Technology in 2018 affiliated to JNTUK University.



PERSONAL DETAILS



	Name	Swetha

	Gender	Female

	Nationality	Indian

	Languages Known	English and Telugu





I hereby declare that all the details and particulars furnished above are true to the best of my knowledge.



Best Regards, Swetha.

In [38]:
df['class'] = "workday_resumes"

In [39]:
df.head()

,File Name,Text Data,class
0,ChinnaSubbarayuduM_Hexaware.docx,Chinna Subbarayudu M\n\nDOB: 06th March 1994\n...,workday_resumes
1,Gopi Krishna_Hexaware.docx,Name : Gopi Krishna Reddy\n\n\t\t\t\t ...,workday_resumes
2,Hari Krishna M_Hexaware.docx,Hari Krishna M\n\n\n\n\n\nSummary:\n\nA result...,workday_resumes
3,Harikrishna Akula_Hexaware.docx,Harikrishna Akula ...,workday_resumes
4,Hima Mendu_Hexaware.docx,HIMA.MENDU\n\n\t \n\n\n\nCareer Objective\n\n...,workday_resumes

In [40]:
df.to_csv("workday_resumes.csv", index=False)

In [41]:
import pandas as pd
import docx2txt
import glob

# Create empty lists to store data and file names
data = []
file_names = []

# Use glob to get paths of all .doc and .docx files in folder
files = glob.glob("C:\\Users\\rajiv\\OneDrive\\Desktop\\resumedataset\\Resumes\\*.docx") + glob.glob("C:\\Users\\rajiv\\OneDrive\\Desktop\\resumedataset\\Resumes\\*.doc")

# Loop through files
for file in files:
    # Get file name and append to file_names list
    file_name = file.split("\\")[-1]
    file_names.append(file_name)
    # Read text data from file and append to data list
    if file_name.endswith('.docx'):
        text = docx2txt.process(file)
    else:
        with open(file, 'rb') as f:
            text = str(f.read())
    data.append(text)

# Create dataframe
df = pd.DataFrame({'File Name': file_names, 'Text Data': data})

In [42]:
df['class'] = "react_dev"

In [43]:
df.to_csv("react_dev.csv", index=False)

In [46]:
workday_resumes=pd.read_csv('workday_resumes.csv')

In [47]:
SQL_Developer=pd.read_csv("SQL_Developer.csv")

In [48]:
people_soft=pd.read_csv("peoplesoft.csv")

In [49]:
react_dev=pd.read_csv("react_dev.csv")

In [50]:
#mereging all the dataset via row one above each other

In [51]:
merged_df = pd.concat([workday_resumes,SQL_Developer,people_soft,react_dev], axis=0)

In [52]:
merged_df = merged_df.reset_index(drop=True)

In [53]:
merged_df.head()

,File Name,Text Data,class
0,ChinnaSubbarayuduM_Hexaware.docx,Chinna Subbarayudu M\n\nDOB: 06th March 1994\n...,workday_resumes
1,Gopi Krishna_Hexaware.docx,Name : Gopi Krishna Reddy\n\n\t\t\t\t ...,workday_resumes
2,Hari Krishna M_Hexaware.docx,Hari Krishna M\n\n\n\n\n\nSummary:\n\nA result...,workday_resumes
3,Harikrishna Akula_Hexaware.docx,Harikrishna Akula ...,workday_resumes
4,Hima Mendu_Hexaware.docx,HIMA.MENDU\n\n\t \n\n\n\nCareer Objective\n\n...,workday_resumes

In [54]:
merged_df.sample(10)

,File Name,Text Data,class
52,Peoplesoft FSCM_R Ahmed.docx,R Ahmed ...,peoplesoft
31,Ramalakshmi K.docx,resume\n\n\n\n\n\n\t\t\t\t\t\t\t\t\t\t\t\tRama...,SQL_Developer
48,Peoplesoft Finance_Rahul Ahuja.docx,Rahul Ahuja\n\n-------------------------------...,peoplesoft
7,Jyotiverma_Heaware.docx,JYOTI VERMA\t\t\t\t\t\n\n\n\nPROFESSIONAL SUMM...,workday_resumes
54,Resume_Subha Santosh_Peoplesoft FSCM.docx,C O N T A C T :\n\n\n\nAddress: Manyata Tech P...,peoplesoft
69,React JS Developer_KotaniDurgaprasad[3_1] (1)-...,Kotani Durga Prasad\n\n\n\n\n\nObjective:\n\n\...,react_dev
75,Reactjs Developer_Pranish Sonone_Musquare Tech...,Pranish Sonone\n\n\t\t\n\n\n\n\n\n\n\n\n\nCare...,react_dev
41,Peoplesoft Admin_srinivasarao.docx,PEOPLESOFT Administrator\n\n\n\n\n\nSRINIVAS.K...,peoplesoft
57,React Developer_Deepakreddy.docx,Kanumuru Deepak Reddy\n\n\n\n\t\n\n\n\nCAREER ...,react_dev
34,Vinod B.docx,SQL AND MSBI DEVELOPER\n\nSQL AND MSBI DEVELOP...,SQL_Developer

In [55]:
merged_df.to_csv('final_resumes_dataset.csv', index=False)

In [56]:
#saving the final dataset

In [57]:
merged_df.shape

(79, 3)